### ISSUE TITLE
Seeing error "KeyError: 'blksize'" in TftpClient upload

### ISSUE THREAD

**Issue by SohanTirpude** [9001/partftpy#1]
Hello @9001,

## Description
While trying to upload file to tftpclient we are seeing below error:

```
File "/Users/x/test.py", line 75, in test_func
    tftp_client.upload(file_name, file_path)
  File "/Users/x/env/lib/python3.10/site-packages/partftpy/TftpClient.py", line 129, in upload
    self.context.start()
  File "/Users/x/env/lib/python3.10/site-packages/partftpy/TftpContexts.py", line 372, in start
    self.cycle()
  File "/Users/x/env/lib/python3.10/site-packages/partftpy/TftpContexts.py", line 247, in cycle
    self.state = self.state.handle(recvpkt, raddress, rport)
  File "/Users/x/env/lib/python3.10/site-packages/partftpy/TftpStates.py", line 562, in handle
    self.context.pending_complete = self.sendDAT()
  File "/Users/x/env/lib/python3.10/site-packages/partftpy/TftpStates.py", line 103, in sendDAT
    blksize = self.context.options["blksize"]
KeyError: 'blksize'
```

## Context
Before moving to this `partftpy` package, we were using `tftpy` package and with that we didn't see this error. 

## Analysis
In fact, it seems in your code base you made the change on this line: https://github.com/9001/partftpy/blob/master/partftpy/TftpStates.py#L103 to get the `blksize` value and but in `tftpy` package, they were using `getBlocksize` on this line: https://github.com/msoulier/tftpy/blob/master/tftpy/TftpStates.py#L100 to return the default value if `blksize` is missing which is defined here: https://github.com/msoulier/tftpy/blob/master/tftpy/TftpContexts.py#L120.

It seems in your code base you updated this code in this commit: https://github.com/9001/partftpy/commit/bef1ea258f215f3d0d9a3eb614f1a372497022c1#diff-315e703babdffcd7bd0095ecae9cab0c4af83bf28d1500f435ef77d12738aad1.

Can you please check this one?

Thank you.

**Comment by 9001** [comment]
Congratulations on being the second person in the world to use this fork 😁 you're right, I only tested the blksize optimization on the server side, since that's the only code I use hehe

I've closed the issue since I think it's been fixed, but let me know if that's not the case.

Also I added a warning in the readme, just to set the right expectations -- I probably won't be a proper maintainer of tftpy going forward, but I'll probably take patches and fix any low-hanging fruit :>

EDIT: i wanna take a quick look at some weird IPv6 behavior on macos before publishing a new version, so not entirely sure when that'll be... probably within a month or so
